/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AG_StonefirepitAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AG_StonefirepitAddonDeed();
			}
		}

		[ Constructable ]
		public AG_StonefirepitAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 10749 );
			ac.Light = LightType.Circle225;
			AddComponent( ac, 0, 0, 0 );

		}

		public AG_StonefirepitAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AG_StonefirepitAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AG_StonefirepitAddon();
			}
		}

		[Constructable]
		public AG_StonefirepitAddonDeed()
		{
			Name = "AG_Stonefirepit";
		}

		public AG_StonefirepitAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}